### PR TITLE
Various UI/UX fixes and improvements

### LINKED ISSUE #1: Graphical bug on wide-screen monitors
2019-03-26 23 23 20 localhost 264fbc93acba

Kinda self-explanatory...

Only one "panel" should be visible at a time

### LINKED ISSUE #12: Ability to resend verification email
Currently, the verification email is sent automatically during the sign up process. If it fails to get to the user, they have no way of verifying their email currently.

### LINKED ISSUE #13: Change password page
Accounts get hacked, you don't like the password you set, it'd be nice to be able to go to login.hack.gt (which apps using Ground Truth can link to) and change my account's password, if it has one.

### PR DESCRIPTION
**Pull request by petschekr**
* Fixes bug where local logins wouldn't clear session variables after successful login causing incorrect information to be autofilled
* Fixes decision page redirect URI for apps with non-HTTP addresses (e.g. AppGT)
* Adds ability to resend verification email
* Adds ability to change password for local accounts
* Fixes widescreen monitor bug (and improves the animation) by animating opacity in addition to translation between signup steps

Closes #1 
Closes #12 
Closes #13

### CODE REVIEW

File: src/auth/auth.ts [hunk 1]
```diff
@@ -91,8 +95,18 @@ app.all("/logout", (request, response) => {
 	}
 });
 
-app.use(passport.initialize());
-app.use(passport.session());
+authRouter.get("/resend/:uuid", validateAndCacheHostName, async (request, response) => {
+	let user = await User.findOne({ uuid: request.params.uuid || "" });
```
Comment (evan10s) [inline src/auth/auth.ts]: const

File: src/auth/auth.ts [hunk 2]
```diff
@@ -91,8 +95,18 @@ app.all("/logout", (request, response) => {
...
-app.use(passport.session());
+authRouter.get("/resend/:uuid", validateAndCacheHostName, async (request, response) => {
+	let user = await User.findOne({ uuid: request.params.uuid || "" });
+	if (user) {
+		await sendVerificationEmail(request, user);
+		const email = user.email
+			.replace(/</g, "&lt;")
+			.replace(/>/g, "&gt;")
+			.replace(/&/g, "&amp;");
+		request.flash("success", `Resent a verification email to ${email}. ${resendVerificationEmailLink(request, user.uuid)}`);
```
Comment (evan10s) [inline src/auth/auth.ts]: This may reveal email addresses to anyone who knows a user's UUID

File: src/auth/auth.ts [hunk 3]
```diff
@@ -327,6 +341,8 @@ OAuthRouter.get("/authorize", authenticateWithRedirect, server.authorization(asy
 	let scopeNames = scopes.map(scope => scope.name);
```
Comment (evan10s) [inline src/auth/auth.ts]: Const

File: src/auth/auth.ts (hunk 2 above)
Comment (petschekr) [reply src/auth/auth.ts]: Ok true but this will only appear if that account does not have a verified email yet (which shouldn't be applicable to many accounts). Also, if they haven't gotten an email, maybe they're checking the wrong email account so I think we should emphasize this. UUIDs aren't common knowledge anyway.

Comment (evan10s) [reply src/auth/auth.ts]: Fair enough
